config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root 'posts#index'

  resources :posts
  resources :comments
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :image

  scope :my_posts, ->(user) { where(user_id: user.id) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user

  def create
    comment = Comment.new(comment_params)

    flash[:alert] = "Error while commenting (#{comment.errors.messages})" unless comment.save

    redirect_to post_path(comment.post_id)
  end

  def destroy
    comment = Comment.find(params[:id])
    post_id = comment.post_id

    flash[:alert] = "Error while deleting (#{comment.errors.messages})" unless comment.delete

    redirect_to post_path(post_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :body)
  end

  def check_user
    comment = Comment.find_by(id: params[:id])

    if comment
      redirect_to root_path if comment.user_id != current_user.id
    elsif params[:comment][:user_id].to_i != current_user.id
      redirect_to root_path
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy update edit new]
  before_action :check_user, only: %i[destroy update edit]

  def index
    @posts = check_my_posts.page(params[:page]).per(5)
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new; end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    post = Post.new(post_params)

    flash[:alert] = "Error while creating (#{post.errors.messages})" unless post.save

    redirect_to root_path
  end

  def update
    post = Post.find(params[:id])

    flash[:alert] = "Error while updating (#{post.errors.messages})" unless post.update(post_params)

    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:id])

    flash[:alert] = "Error while deleting (#{post.errors.messages})" unless post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :name, :body, :image)
  end

  def check_user
    post = Post.find(params[:id])

    redirect_to root_path if post.user_id != current_user.id
  rescue StandardError
    p 'The post is not found'

    redirect_to root_path
  end

  def check_my_posts
    if params[:my_posts]
      Post.my_posts(current_user)
    else
      Post.all
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_alerts.html.erb
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>

      <h4>Subheading</h4>
      <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

      <h4>Subheading</h4>
      <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

      <h4>Subheading</h4>
      <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="bg-dark mb-3">
  <div class="container">
    <nav class="navbar navbar-expand-xl navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>">SA: test project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse show" id="navbarDark">
          <ul class="navbar-nav me-auto mb-2 mb-xl-0">
            <li class="nav-item">
              <a class="nav-link <%= current_user ? 'active' : 'disabled' %>" aria-current="page" href="<%= root_path %>">All posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link <%= current_user ? 'active' : 'disabled' %>" aria-current="page" href="<%= root_path(my_posts: true) %>">My posts</a>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <%= link_to 'Exit', destroy_user_session_path, data: { "turbo-method": :delete }, class: 'nav-link active' %>
              </li>
            <% else %>
              <li class="nav-item">
                <a class="nav-link active" href="<%= new_user_session_path %>">
                  Sign in
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="<%= new_user_registration_path %>">
                  Sign up
                </a>
              </li>
            <% end %>
          </ul>

          <!--        <form class="d-flex">-->
          <!--          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
          <!--          <button class="btn btn-outline-light" type="submit">Search</button>-->
          <!--        </form>-->
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_send_message.html.erb
<div class="container mb-3 card border-dark padding_form">
  <%= form_with(url: posts_path, model: @post, local: true, remote: false) do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="form-floating mb-3">
      <%= form.text_field :name, class: 'form-control', placeholder: 'Title' %>
      <%= form.label :name %>
    </div>
    <div class="form-floating mb-3">
      <%= form.text_area :body, class: 'form-control', placeholder: 'Comment', style: 'height: 100px' %>
      <%= form.label :body %>
    </div>
    <div>
      <%= form.file_field :image, class: 'mb-3' %>
    </div>

    <%= form.submit 'Create post' %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Sa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/alerts' %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container mb-3 card border-dark padding_form">
  <%= form_with(url: post_path(@post), model: @post, local: true, remote: false, method: :put) do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <div class="form-floating mb-3">
      <%= form.text_field :name, class: 'form-control', placeholder: 'Title' %>
      <%= form.label :name %>
    </div>
    <div class="form-floating mb-3">
      <%= form.text_area :body, class: 'form-control', placeholder: 'Body', style: 'height: 100px' %>
      <%= form.label :body %>
    </div>
    <div>
      <%= form.file_field :image, class: 'mb-3' %>
    </div>

    <%= form.submit 'Update post' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render partial: 'layouts/send_message' if current_user %>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <% @posts.each do |post| %>
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-5 col-sm-4">
              <% if post.image.present? %>
                <%= image_tag post.image, class: 'img-fluid w-100 custom_img' %>
              <% end %>
            </div>
            <div class="col-7 col-sm-8">
              <div class="card-body">
                <h5 class="card-title"><%= post.name %></h5>
                <p class="card-text"><%= post.body %></p>
                <div class="bottom-card-element">
                  <%= link_to 'View', post_path(post), class: 'btn btn-dark' %>
                  <p class="card-text"><small class="text-muted"><%= post.updated_at %> by <%= post.user.nickname %></small></p>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  </div>

  <%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="container mb-3">
  <div class="card">

    <% if @post.image.present? %>
      <%= image_tag @post.image, class: 'card-img-top' %>
    <% end %>
    <div class="card-body mb-4">
      <h5 class="card-title"><%= @post.name %></h5>
      <p class="card-text"><%= @post.body %></p>
      <p class="card-text"><small class="text-muted"><%= @post.updated_at %> by <%= @post.user.nickname %></small></p>
    </div>

    <% if current_user == @post.user %>
      <div class="bottom-card-element">
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-success' %>
        <%= link_to 'Delete', post_path(@post), data: { "turbo-method": :delete, "turbo-confirm": 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

<% if current_user %>
  <div class="container mb-3 card border-dark padding_form">
    <%= form_with(url: comments_path, model: @comment, local: true, remote: false) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.hidden_field :post_id, value: @post.id %>

      <div class="form-floating mb-3">
        <%= form.text_area :body, class: 'form-control', placeholder: 'Body', style: 'height: 100px' %>
        <%= form.label :body %>
      </div>

      <%= form.submit 'Send' %>
    <% end %>
  </div>
<% end %>

<div class="container mb-3">
  <% @post.comments.each do |comment| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= comment.user.nickname %></h5>
        <p class="card-text"><%= comment.body %></p>
        <% if comment.user == current_user %>
          <%= link_to 'Delete the comment', comment_path(comment), data: { "turbo-method": :delete, "turbo-confirm": 'Are you sure?' }, class: 'btn btn-danger' %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <%= comment.updated_at %>
      </div>
    </div>
  <% end %>
</div>